force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Assignment__c/Meeting_Assignment__c.object-meta.xml
<CustomObject>
    <label>Meeting Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>MA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Assignment__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Assignments</relationshipLabel>
    <relationshipName>Meeting_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting_Assignment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Meeting Assignments</relationshipLabel>
    <relationshipName>Meeting_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MeetingAssignmentsController.cls
public with sharing class MeetingAssignmentsController {

    @AuraEnabled(cacheable=true)
    public static List<Meeting__c> getMAList(){
        SObjectAccessDecision securityDecision = Security.stripInaccessible(
            AccessType.READABLE,
            [SELECT Id, Meeting__r.Name, Participant__r.Name FROM Meeting_Assignment__c LIMIT 50000]
        );
        
        return securityDecision.getRecords();
    }

    @AuraEnabled
    public static void sendInvite(Id assignmentId){
        Meeting_Assignment__c assignment = (Meeting_Assignment__c)SecurityService.getFirstSecureRecord(
            [
                SELECT Id, Meeting__r.Name, Participant__r.Name, Participant__r.Email__c
                FROM Meeting_Assignment__c
                WHERE Id = :assignmentId
            ],
            false
        );

        MessagingService.sendInvite(assignment.Meeting__r.Name, new Map<String, String>{assignment.Participant__r.Email__c => assignment.Participant__r.Name});
    }
}